const { logger } = require('../utils/logger');
const api = require('../api');
const { z } = require('zod');
const { handleZabbixError } = require('../utils/errors');

// Trigger tag schema based on official API
const triggerTagSchema = z.object({
    tag: z.string().min(1).describe('Trigger tag name'),
    value: z.string().optional().default('').describe('Trigger tag value')
});

// Enhanced trigger schema with all official properties
const triggerSchema = z.object({
    triggerid: z.string().optional().describe('ID of the trigger (read-only for updates)'),
    description: z.string().min(1).describe('Name of the trigger'),
    expression: z.string().min(1).describe('Reduced trigger expression'),
    event_name: z.string().optional().describe('Event name generated by the trigger'),
    opdata: z.string().optional().describe('Operational data'),
    comments: z.string().optional().describe('Additional description of the trigger'),
    error: z.string().optional().describe('Error text if there have been problems (read-only)'),
    flags: z.number().int().optional().describe('Origin of trigger: 0=plain, 4=discovered (read-only)'),
    lastchange: z.number().int().optional().describe('Time when trigger last changed state (read-only)'),
    priority: z.number().int().min(0).max(5).optional().default(0).describe('Severity: 0=not classified, 1=information, 2=warning, 3=average, 4=high, 5=disaster'),
    state: z.number().int().optional().describe('Trigger state: 0=up to date, 1=unknown (read-only)'),
    status: z.number().int().optional().default(0).describe('Status: 0=enabled, 1=disabled'),
    templateid: z.string().optional().describe('ID of parent template trigger (read-only)'),
    type: z.number().int().optional().default(0).describe('Multiple events: 0=no, 1=yes'),
    url: z.string().optional().describe('URL associated with the trigger'),
    url_name: z.string().optional().describe('Label for the URL'),
    value: z.number().int().optional().describe('Current state: 0=OK, 1=problem (read-only)'),
    recovery_mode: z.number().int().optional().default(0).describe('OK event generation: 0=expression, 1=recovery expression, 2=none'),
    recovery_expression: z.string().optional().describe('Reduced trigger recovery expression'),
    correlation_mode: z.number().int().optional().default(0).describe('OK event closes: 0=all problems, 1=tag values match'),
    correlation_tag: z.string().optional().describe('Tag for matching'),
    manual_close: z.number().int().optional().default(0).describe('Allow manual close: 0=no, 1=yes'),
    uuid: z.string().optional().describe('Universal unique identifier for template linking'),
    tags: z.array(triggerTagSchema).optional().describe('Trigger tags array')
});

function registerTools(server) {
    // Get triggers with comprehensive schema
    server.tool(
        'zabbix_get_triggers',
        'Get triggers from Zabbix with filtering and output options',
        {
            triggerids: z.array(z.string()).optional().describe('Return only triggers with the given trigger IDs'),
            hostids: z.array(z.string()).optional().describe('Return only triggers that belong to the given hosts'),
            groupids: z.array(z.string()).optional().describe('Return only triggers that belong to hosts in the given host groups'),
            templateids: z.array(z.string()).optional().describe('Return only triggers that belong to the given templates'),
            output: z.array(z.string()).optional().default(['triggerid', 'description', 'expression', 'priority', 'status', 'value']).describe('Object properties to be returned'),
            selectHosts: z.array(z.string()).optional().describe('Return hosts that the trigger belongs to'),
            selectItems: z.array(z.string()).optional().describe('Return items that are used in the trigger'),
            selectTags: z.array(z.string()).optional().describe('Return trigger tags'),
            selectFunctions: z.array(z.string()).optional().describe('Return functions used in the trigger'),
            selectGroups: z.array(z.string()).optional().describe('Return host groups that the trigger belongs to'),
            selectTriggerDiscovery: z.array(z.string()).optional().describe('Return trigger discovery data'),
            selectDependencies: z.array(z.string()).optional().describe('Return triggers that this trigger depends on'),
            selectDiscoveryRule: z.array(z.string()).optional().describe('Return discovery rule that created the trigger'),
            filter: z.record(z.any()).optional().describe('Return only triggers that match the given filter'),
            search: z.record(z.any()).optional().describe('Return only triggers that match the given wildcard search'),
            searchByAny: z.boolean().optional().describe('Return results that match any of the criteria in search'),
            searchWildcardsEnabled: z.boolean().optional().describe('Return results that contain wildcards'),
            startSearch: z.boolean().optional().describe('Return results that start with the criteria in search'),
            excludeSearch: z.boolean().optional().describe('Return results that do not match criteria in search'),
            sortfield: z.array(z.string()).optional().default(['priority']).describe('Sort the result by the given properties'),
            sortorder: z.enum(['ASC', 'DESC']).optional().default('DESC').describe('Sort order'),
            limit: z.number().int().positive().optional().describe('Limit the number of records returned'),
            countOutput: z.boolean().optional().describe('Return count of triggers instead of trigger data'),
            preservekeys: z.boolean().optional().describe('Use trigger IDs as keys in the resulting array'),
            monitored: z.boolean().optional().describe('Return only enabled triggers that belong to monitored hosts'),
            only_true: z.boolean().optional().describe('Return only triggers that are in problem state'),
            min_severity: z.number().int().min(0).max(5).optional().describe('Return only triggers with severity greater or equal'),
            expandDescription: z.boolean().optional().default(true).describe('Expand macros in the trigger description'),
            expandExpression: z.boolean().optional().describe('Expand macros in the trigger expression'),
            expandComment: z.boolean().optional().describe('Expand macros in the trigger comments'),
            inherited: z.boolean().optional().describe('Return triggers inherited from templates'),
            templated: z.boolean().optional().describe('Return only triggers that belong to templates'),
            dependentTriggers: z.boolean().optional().describe('Return triggers with dependencies'),
            withUnacknowledgedEvents: z.boolean().optional().describe('Return triggers with unacknowledged events'),
            withAcknowledgedEvents: z.boolean().optional().describe('Return triggers with acknowledged events'),
            withLastEventUnacknowledged: z.boolean().optional().describe('Return triggers whose last event is unacknowledged'),
            skipDependent: z.boolean().optional().describe('Skip dependent triggers'),
            lastChangeSince: z.number().int().optional().describe('Return triggers that changed after given timestamp'),
            lastChangeTill: z.number().int().optional().describe('Return triggers that changed before given timestamp'),
            tags: z.array(z.object({
                tag: z.string().describe('Tag name'),
                value: z.string().optional().describe('Tag value'),
                operator: z.enum(['0', '1', '2', '3']).optional().describe('Tag operator: 0=like, 1=equal, 2=not like, 3=not equal')
            })).optional().describe('Return only triggers with given tags'),
            evaltype: z.enum(['0', '2']).optional().describe('Tag evaluation: 0=AND/OR, 2=OR')
        },
        async (args) => {
            try {
                const params = { ...args };
                
                const apiParams = {
                    output: params.output || ['triggerid', 'description', 'expression', 'priority', 'status', 'value'],
                    sortfield: params.sortfield || ['priority'],
                    sortorder: params.sortorder || 'DESC',
                    expandDescription: params.expandDescription !== undefined ? params.expandDescription : true
                };

                // Basic filtering
                if (params.triggerids) apiParams.triggerids = params.triggerids;
                if (params.hostids) apiParams.hostids = params.hostids;
                if (params.groupids) apiParams.groupids = params.groupids;
                if (params.templateids) apiParams.templateids = params.templateids;
                
                // Enhanced selection options
                if (params.selectHosts) apiParams.selectHosts = params.selectHosts;
                if (params.selectItems) apiParams.selectItems = params.selectItems;
                if (params.selectTags) apiParams.selectTags = params.selectTags;
                if (params.selectFunctions) apiParams.selectFunctions = params.selectFunctions;
                if (params.selectGroups) apiParams.selectGroups = params.selectGroups;
                if (params.selectTriggerDiscovery) apiParams.selectTriggerDiscovery = params.selectTriggerDiscovery;
                if (params.selectDependencies) apiParams.selectDependencies = params.selectDependencies;
                if (params.selectDiscoveryRule) apiParams.selectDiscoveryRule = params.selectDiscoveryRule;
                
                // Search and filtering
                if (params.filter) apiParams.filter = params.filter;
                if (params.search) apiParams.search = params.search;
                if (params.searchByAny !== undefined) apiParams.searchByAny = params.searchByAny;
                if (params.searchWildcardsEnabled !== undefined) apiParams.searchWildcardsEnabled = params.searchWildcardsEnabled;
                if (params.startSearch !== undefined) apiParams.startSearch = params.startSearch;
                if (params.excludeSearch !== undefined) apiParams.excludeSearch = params.excludeSearch;
                if (params.tags) apiParams.tags = params.tags;
                if (params.evaltype) apiParams.evaltype = params.evaltype;
                
                // Output options
                if (params.limit) apiParams.limit = params.limit;
                if (params.countOutput !== undefined) apiParams.countOutput = params.countOutput;
                if (params.preservekeys !== undefined) apiParams.preservekeys = params.preservekeys;
                
                // Advanced filtering
                if (params.monitored !== undefined) apiParams.monitored = params.monitored;
                if (params.only_true !== undefined) apiParams.only_true = params.only_true;
                if (params.min_severity !== undefined) apiParams.min_severity = params.min_severity;
                if (params.inherited !== undefined) apiParams.inherited = params.inherited;
                if (params.templated !== undefined) apiParams.templated = params.templated;
                if (params.dependentTriggers !== undefined) apiParams.dependentTriggers = params.dependentTriggers;
                if (params.withUnacknowledgedEvents !== undefined) apiParams.withUnacknowledgedEvents = params.withUnacknowledgedEvents;
                if (params.withAcknowledgedEvents !== undefined) apiParams.withAcknowledgedEvents = params.withAcknowledgedEvents;
                if (params.withLastEventUnacknowledged !== undefined) apiParams.withLastEventUnacknowledged = params.withLastEventUnacknowledged;
                if (params.skipDependent !== undefined) apiParams.skipDependent = params.skipDependent;
                if (params.lastChangeSince) apiParams.lastChangeSince = params.lastChangeSince;
                if (params.lastChangeTill) apiParams.lastChangeTill = params.lastChangeTill;
                
                // Expansion options
                if (params.expandExpression !== undefined) apiParams.expandExpression = params.expandExpression;
                if (params.expandComment !== undefined) apiParams.expandComment = params.expandComment;

                const triggers = await api.getTriggers(apiParams);
                
                logger.info(`Retrieved ${triggers.length} triggers`);
                return {
                    content: [{
                        type: 'text',
                        text: `Found ${triggers.length} triggers:\n\n${JSON.stringify(triggers, null, 2)}`
                    }]
                };
            } catch (error) {
                const enhancedError = handleZabbixError(error, 'error_getting_triggers', args);
                logger.error('Error getting triggers::', enhancedError.message);
                logger.debug('Full error details:', enhancedError.details);
                throw new Error(enhancedError.message);
            }
        }
    );

    // Create trigger with comprehensive schema
    server.tool(
        'zabbix_create_trigger',
        'Create a new trigger in Zabbix with complete property support',
        {
            description: z.string().min(1).describe('Name of the trigger'),
            expression: z.string().min(1).describe('Reduced trigger expression'),
            event_name: z.string().optional().describe('Event name generated by the trigger'),
            opdata: z.string().optional().describe('Operational data'),
            comments: z.string().optional().describe('Additional description of the trigger'),
            priority: z.number().int().min(0).max(5).optional().default(0).describe('Severity: 0=not classified, 1=information, 2=warning, 3=average, 4=high, 5=disaster'),
            status: z.number().int().optional().default(0).describe('Status: 0=enabled, 1=disabled'),
            type: z.number().int().optional().default(0).describe('Multiple events: 0=no, 1=yes'),
            url: z.string().optional().describe('URL associated with the trigger'),
            url_name: z.string().optional().describe('Label for the URL'),
            recovery_mode: z.number().int().min(0).max(2).optional().default(0).describe('OK event generation: 0=expression, 1=recovery expression, 2=none'),
            recovery_expression: z.string().optional().describe('Reduced trigger recovery expression'),
            correlation_mode: z.number().int().min(0).max(1).optional().default(0).describe('OK event closes: 0=all problems, 1=tag values match'),
            correlation_tag: z.string().optional().describe('Tag for matching'),
            manual_close: z.number().int().min(0).max(1).optional().default(0).describe('Allow manual close: 0=no, 1=yes'),
            tags: z.array(triggerTagSchema).optional().describe('Trigger tags array'),
            dependencies: z.array(z.object({
                triggerid: z.string().describe('ID of trigger that this trigger depends on')
            })).optional().describe('Trigger dependencies')
        },
        async (args) => {
            try {
                const params = { ...args };
                
                const result = await api.createTrigger(params);
                
                logger.info(`Created trigger: ${params.description} (ID: ${result.triggerids[0]})`);
                return {
                    content: [{
                        type: 'text',
                        text: `Successfully created trigger "${params.description}" with ID: ${result.triggerids[0]}`
                    }]
                };
            } catch (error) {
                const enhancedError = handleZabbixError(error, 'error_creating_trigger', args);
                logger.error('Error creating trigger::', enhancedError.message);
                logger.debug('Full error details:', enhancedError.details);
                throw new Error(enhancedError.message);
            }
        }
    );

    // Update trigger with comprehensive schema
    server.tool(
        'zabbix_update_trigger',
        'Update an existing trigger in Zabbix with complete property support',
        {
            triggerid: z.string().describe('ID of the trigger to update'),
            description: z.string().optional().describe('Name of the trigger'),
            expression: z.string().optional().describe('Reduced trigger expression'),
            event_name: z.string().optional().describe('Event name generated by the trigger'),
            opdata: z.string().optional().describe('Operational data'),
            comments: z.string().optional().describe('Additional description of the trigger'),
            priority: z.number().int().min(0).max(5).optional().describe('Severity: 0=not classified, 1=information, 2=warning, 3=average, 4=high, 5=disaster'),
            status: z.number().int().optional().describe('Status: 0=enabled, 1=disabled'),
            type: z.number().int().optional().describe('Multiple events: 0=no, 1=yes'),
            url: z.string().optional().describe('URL associated with the trigger'),
            url_name: z.string().optional().describe('Label for the URL'),
            recovery_mode: z.number().int().min(0).max(2).optional().describe('OK event generation: 0=expression, 1=recovery expression, 2=none'),
            recovery_expression: z.string().optional().describe('Reduced trigger recovery expression'),
            correlation_mode: z.number().int().min(0).max(1).optional().describe('OK event closes: 0=all problems, 1=tag values match'),
            correlation_tag: z.string().optional().describe('Tag for matching'),
            manual_close: z.number().int().min(0).max(1).optional().describe('Allow manual close: 0=no, 1=yes'),
            tags: z.array(triggerTagSchema).optional().describe('Trigger tags array'),
            dependencies: z.array(z.object({
                triggerid: z.string().describe('ID of trigger that this trigger depends on')
            })).optional().describe('Trigger dependencies')
        },
        async (args) => {
            try {
                const params = { ...args };
                
                const result = await api.updateTrigger(params);
                
                logger.info(`Updated trigger ID ${params.triggerid}`);
                return {
                    content: [{
                        type: 'text',
                        text: `Successfully updated trigger ID ${params.triggerid}`
                    }]
                };
            } catch (error) {
                const enhancedError = handleZabbixError(error, 'error_updating_trigger', args);
                logger.error('Error updating trigger::', enhancedError.message);
                logger.debug('Full error details:', enhancedError.details);
                throw new Error(enhancedError.message);
            }
        }
    );

    // Delete triggers
    server.tool(
        'zabbix_delete_triggers',
        'Delete triggers from Zabbix',
        {
            triggerids: z.array(z.string()).min(1).describe('Array of trigger IDs to delete')
        },
        async (args) => {
            try {
                const { triggerids } = args;
                
                const result = await api.deleteTriggers(triggerids);
                
                logger.info(`Deleted ${triggerids.length} triggers`);
                return {
                    content: [{
                        type: 'text',
                        text: `Successfully deleted ${triggerids.length} triggers: ${triggerids.join(', ')}`
                    }]
                };
            } catch (error) {
                const enhancedError = handleZabbixError(error, 'error_deleting_triggers', args);
                logger.error('Error deleting triggers::', enhancedError.message);
                logger.debug('Full error details:', enhancedError.details);
                throw new Error(enhancedError.message);
            }
        }
    );

    logger.info('Enhanced triggers tools registered successfully');
}

module.exports = { registerTools }; 